// Code generated by protoc-gen-go. DO NOT EDIT.
// source: WebsocketNonSystem.proto

package kcwiki_msgtransfer_protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WebsocketNonSystem struct {
	Module               string   `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebsocketNonSystem) Reset()         { *m = WebsocketNonSystem{} }
func (m *WebsocketNonSystem) String() string { return proto.CompactTextString(m) }
func (*WebsocketNonSystem) ProtoMessage()    {}
func (*WebsocketNonSystem) Descriptor() ([]byte, []int) {
	return fileDescriptor_WebsocketNonSystem_baedf3bbdde7cea6, []int{0}
}
func (m *WebsocketNonSystem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebsocketNonSystem.Unmarshal(m, b)
}
func (m *WebsocketNonSystem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebsocketNonSystem.Marshal(b, m, deterministic)
}
func (dst *WebsocketNonSystem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebsocketNonSystem.Merge(dst, src)
}
func (m *WebsocketNonSystem) XXX_Size() int {
	return xxx_messageInfo_WebsocketNonSystem.Size(m)
}
func (m *WebsocketNonSystem) XXX_DiscardUnknown() {
	xxx_messageInfo_WebsocketNonSystem.DiscardUnknown(m)
}

var xxx_messageInfo_WebsocketNonSystem proto.InternalMessageInfo

func (m *WebsocketNonSystem) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *WebsocketNonSystem) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*WebsocketNonSystem)(nil), "kcwiki.msgtransfer.protobuf.WebsocketNonSystem")
}

func init() {
	proto.RegisterFile("WebsocketNonSystem.proto", fileDescriptor_WebsocketNonSystem_baedf3bbdde7cea6)
}

var fileDescriptor_WebsocketNonSystem_baedf3bbdde7cea6 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x08, 0x4f, 0x4d, 0x2a,
	0xce, 0x4f, 0xce, 0x4e, 0x2d, 0xf1, 0xcb, 0xcf, 0x0b, 0xae, 0x2c, 0x2e, 0x49, 0xcd, 0xd5, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0xce, 0x4e, 0x2e, 0xcf, 0xcc, 0xce, 0xd4, 0xcb, 0x2d, 0x4e,
	0x2f, 0x29, 0x4a, 0xcc, 0x2b, 0x4e, 0x4b, 0x2d, 0x82, 0xc8, 0x24, 0x95, 0xa6, 0x29, 0x39, 0x70,
	0x09, 0x61, 0x6a, 0x14, 0x12, 0xe3, 0x62, 0xcb, 0xcd, 0x4f, 0x29, 0xcd, 0x49, 0x95, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf2, 0x84, 0x84, 0xb8, 0x58, 0x52, 0x12, 0x4b, 0x12, 0x25, 0x98,
	0xc0, 0xa2, 0x60, 0xb6, 0x93, 0x36, 0x17, 0x1f, 0xcc, 0x34, 0x88, 0xb1, 0x4e, 0xe2, 0x98, 0x26,
	0x06, 0x80, 0x24, 0x02, 0x18, 0x93, 0xd8, 0xc0, 0x2a, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xae, 0x06, 0xec, 0xb1, 0xae, 0x00, 0x00, 0x00,
}
